name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Replace with your project's Python version

    - name: Install dependencies and run tests
      shell: bash
      run: |
        # Create and activate the virtual environment
        python -m venv venv
        source venv/bin/activate

        # Upgrade pip and install dependencies
        pip install --upgrade pip
        pip install -r requirements.txt

        # Download NLTK data
        python -c "import nltk; nltk.download('stopwords', quiet=True)"

        # Download the 20 Newsgroups dataset
        python -c "from sklearn.datasets import fetch_20newsgroups; fetch_20newsgroups(subset='all')"

        # Run the application in the background
        nohup flask run --host=0.0.0.0 --port=3000 &

        # Wait for the application to start
        sleep 30

        # Send a POST request with form data
        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST http://localhost:3000/search \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "query=machine learning")

        # Separate the body and the status code
        HTTP_BODY=$(echo "$RESPONSE" | sed '$d')
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1 | cut -d':' -f2)

        echo "HTTP Status: $HTTP_STATUS"
        echo "Response Body: $HTTP_BODY"

        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Request failed with status $HTTP_STATUS"
          exit 1
        fi

        # Check if the response contains the expected keys
        echo "$HTTP_BODY" | grep '"documents"' > /dev/null
        echo "$HTTP_BODY" | grep '"similarities"' > /dev/null
        echo "$HTTP_BODY" | grep '"indices"' > /dev/null

        # Check if the number of returned documents is 5
        NUM_DOCS=$(echo "$HTTP_BODY" | python -c "import sys, json; print(len(json.load(sys.stdin)['documents']))")
        if [ "$NUM_DOCS" -ne 5 ]; then
          echo "Expected 5 documents, got $NUM_DOCS"
          exit 1
        fi

        echo "Test passed: Received 5 documents with expected keys."
